import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getMachineNames } from "./utils/utils"

import SideBar from "./components/SideBarLayout"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const machines = await getMachineNames()
  const navItems = Object.keys(machines).map((machine) => {
    return {
      name: machine,
      href: "/machine/" + machine,
      current: false
    }
  })  

  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar navItems={navItems}>{children}</SideBar>
      </body>
    </html>
  );
}
